In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.array([[0, 1],
       [2, 3],
       [4, 5]])
poly = PolynomialFeatures(2)
##poly simply is initialization, sets degree as 2 in this example.
poly.fit_transform(X)
##GOAL IS TO RECREATE THIS

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

Implement the following function that generates the polynomial and interaction
features for a given degree of the polynomial.

polynomialFeatures(X, degree)

Argument:

    X : ndarray

        A numpy array with rows representing data samples and columns

        representing features (d-dimensional feature).

    degree : integer
        
        The degree of the polynomial features. Default = 1.
        

Returns:
    
    A new feature matrix consisting of all polynomial combinations of the features
    with degree equal to the specified degree. For example, if an input sample is two
    dimensional and of the form [a, b], the degree-2 polynomial features are [a, b, a2,ab, b2].

In [6]:
def polynomialFeatures(x,degree):
        x_t = x.T
        features = np.ones(len(x))
        for degree in range(1, degree + 1):
            for items in it.combinations_with_replacement(x_t, degree):
                features = np.vstack((features,ft.reduce(lambda x, y: x * y, items)))
        return features.T

In [16]:
import itertools as it
import numpy as np
import functools as ft

X = np.array([[0, 1],
       [2, 3],
       [4, 5]])
samples, features= X.shape
print(X.T)
poly = polynomialFeatures(X,2)
print(poly)

[[0 2 4]
 [1 3 5]]
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [ ]:
def polynomialFeatures(x,degree):
    #by default: interaction_only=false, include_bias=true, order='C'
    #fitting
    samples, features= x.shape
    
    #this can be done in 6 lines with itertools.combination_with_replacement
    combs= it.chain(it.combinations_with_replacement(x, degree) for i in range(0, degree+1))
    input_features = features
    outputfeatures = sum(1 for  in combs)

    print(input_features)
    print(output_features)
    #fit returns combs, input feature number, output feature number. combs is our new "x". i
    polynomials=combs
    final= np.empty((samples,output_features), dtype=X.dtype)
    for i, comb in enumerate(combs):
        final[:, i] = x[:, comb].prod(1)
    return final